### ISSUE TITLE
Oddly shaped files are truncated

### ISSUE THREAD

**Issue by stucka** [cknoll/imagedirpreview#1]
The rendering system appears to fail when the aspect ratio is too extreme. For example, some three-word logos written horizontally get truncated on their right side.

Thank you for this, though! This works for most of what I needed.

**Comment by cknoll** [comment]
Thank you for your feedback. Honestly, the probability that I will fix this soon is quite low, due to shifted priorities. But, anyway the probability that *someone* will fix this increases if it is easy to reproduce the problem, e.g. with a linked logo-file.

Also: Glad to hear that in general you find it useful.
